version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - webshop-net
    command: ["start-dev"]

  db:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - webshop-net

  customer:
    build:
      context: ./customer
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: customer
    environment:
      DATABASE_HOST: db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: customerdb
      DATABASE_PORT: 5432
    ports:
      - "8081:8081"
    depends_on:
      - db
    volumes:
      - ./workspace:/workspace
    networks:
      - webshop-net

  product:
    build:
      context: ./product
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: product
    environment:
      DATABASE_HOST: db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: productdb
      DATABASE_PORT: 5432
    ports:
      - "8082:8082"
    depends_on:
      - db
    volumes:
      - ./workspace:/workspace
    networks:
      - webshop-net

  order:
    build:
      context: ./order
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: order
    environment:
      DATABASE_HOST: db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: orderdb
      DATABASE_PORT: 5432
    ports:
      - "8083:8083"
    depends_on:
      - db
    volumes:
      - ./workspace:/workspace
    networks:
      - webshop-net

networks:
  webshop-net:

volumes:
  postgres-data:
